# Generated by Django 4.1.1 on 2022-09-12 04:38

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('license_number', models.BigIntegerField()),
                ('codename', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('route', models.CharField(choices=[('Temuki', 'Temuki'), ('Kazirbazar', 'Kazirbazar'), ('Chondipul', 'Chondipul'), ('Modina Market', 'Modina Market'), ('Rekab Bazar', 'Rekab Bazar'), ('Subid Bazar', 'Subid Bazar'), ('Humayun Rashid Chattar', 'Humayun Rashid Chattar')], default='', max_length=230)),
                ('profession', models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Staff', 'Staff')], default='', max_length=230)),
            ],
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('ip', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=13232)),
                ('ID', models.CharField(default='', max_length=200)),
                ('profession', models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Staff', 'Staff')], default='', max_length=230)),
                ('route', models.CharField(choices=[('Temuki', 'Temuki'), ('Kazirbazar', 'Kazirbazar'), ('Chondipul', 'Chondipul'), ('Modina Market', 'Modina Market'), ('Rekab Bazar', 'Rekab Bazar'), ('Subid Bazar', 'Subid Bazar'), ('Humayun Rashid Chattar', 'Humayun Rashid Chattar')], default='', max_length=230)),
                ('timeslot', models.CharField(choices=[('08:00 AM', '08:00 AM'), ('09:00 AM', '09:00 AM'), ('12:00 PM', '12:00 PM'), ('01:00 PM', '01:00 PM')], default='', max_length=230)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Demand',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=25)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('start_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('images', models.ImageField(upload_to='images/')),
                ('route', models.CharField(choices=[('Temuki', 'Temuki'), ('Kazirbazar', 'Kazirbazar'), ('Chondipul', 'Chondipul'), ('Modina Market', 'Modina Market'), ('Rekab Bazar', 'Rekab Bazar'), ('Subid Bazar', 'Subid Bazar'), ('Humayun Rashid Chattar', 'Humayun Rashid Chattar')], default='', max_length=230)),
                ('timeslot', models.CharField(choices=[('08:00 AM', '08:00 AM'), ('09:00 AM', '09:00 AM'), ('12:00 PM', '12:00 PM'), ('01:00 PM', '01:00 PM')], default='', max_length=230)),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('ip', models.AutoField(primary_key=True, serialize=False)),
                ('full_Name', models.CharField(max_length=100)),
                ('profession', models.CharField(choices=[('student', 'student'), ('Teacher', 'Teacher'), ('Staff', 'Staff')], default='', max_length=230)),
                ('ID', models.BigIntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.BigIntegerField()),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Support',
            },
        ),
        migrations.CreateModel(
            name='Driver_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(default='', max_length=50)),
                ('contact_number', models.IntegerField()),
                ('Bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.bus_info')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
